        !COMPILER-GENERATED INTERFACE MODULE: Wed May 18 11:05:29 2011
        MODULE D1MACH__genmod
          INTERFACE 
            FUNCTION D1MACH(IDUM) RESULT(D1MACH_0)
              INTEGER(KIND=4) :: IDUM
              REAL(KIND=8) :: D1MACH_0
            END FUNCTION D1MACH
          END INTERFACE 
        END MODULE D1MACH__genmod
