        !COMPILER-GENERATED INTERFACE MODULE: Thu Nov 11 12:25:31 2010
        MODULE ILASCH__genmod
          INTERFACE 
            FUNCTION ILASCH(STRING) RESULT(ILASCH_0)
              CHARACTER(*) :: STRING
              INTEGER(KIND=4) :: ILASCH_0
            END FUNCTION ILASCH
          END INTERFACE 
        END MODULE ILASCH__genmod
