        !COMPILER-GENERATED INTERFACE MODULE: Thu Nov 11 12:25:31 2010
        MODULE UPCASE__genmod
          INTERFACE 
            FUNCTION UPCASE(ISTR,ILEN) RESULT(UPCASE_0)
              CHARACTER(*) :: ISTR
              INTEGER(KIND=4) :: ILEN
              CHARACTER(*) :: UPCASE
            END FUNCTION UPCASE
          END INTERFACE 
        END MODULE UPCASE__genmod
